### ISSUE TITLE
Activate EdX synchronization for this client 💰

### ISSUE THREAD

**Issue by JulienBara-360** [360Learning/GitStats_Sandbox#145]
The client paid for the integration, activate EdX synchronization for him. Credentials in LastPass.

**Comment by all-servers** [comment]
@JulienBara-360

A PR adds or moves a line or a file that contains the word "company".
As described [here](https://trello.com/c/W6yarD9n/273-implementing-features-at-group-level), it should be avoided if possible.
- https://github.com/360Learning/GitStats_Sandbox/pull/147

**Comment by all-servers** [comment]
@JulienBara-360

A PR adds or moves a line or a file that contains the word "company".
As described [here](https://trello.com/c/W6yarD9n/273-implementing-features-at-group-level), it should be avoided if possible.
- https://github.com/360Learning/GitStats_Sandbox/pull/148

**Comment by all-servers** [comment]
@louis-sanna

A PR adds or moves a line or a file that contains the word "company".
As described [here](https://trello.com/c/W6yarD9n/273-implementing-features-at-group-level), it should be avoided if possible.
- https://github.com/360Learning/GitStats_Sandbox/pull/150

**Comment by all-servers** [comment]
@eripoche If you follow [this card](https://trello.com/c/zz1eojzD/439-activating-an-integration-for-your-group), you should be able to activate the integration and set up the credentials in production using the backoffice and the integration administration panel within the platform.

Tip: if you want to set up a dedicated docker meant to be eternal until the pilot phase is validated by the client please use the `containerSynchroActivation` label instead.
