### ISSUE TITLE
Test bug

### ISSUE THREAD

**Issue by maximepiard** [360Learning/GitStats_Sandbox#161]

**Comment by all-servers** [comment]
@eripoche If you follow [this card](https://trello.com/c/zz1eojzD/439-activating-an-integration-for-your-group), you should be able to activate the integration and set up the credentials in production using the backoffice and the integration administration panel within the platform.

Tip: if you want to set up a dedicated docker meant to be eternal until the pilot phase is validated by the client please use the `containerSynchroActivation` label instead.
